// <auto-generated />
using Data.Persistance;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180311200921_Rules")]
    partial class Rules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Domain.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Property");

                    b.Property<int>("RuleId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("Domain.Outcomes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Property");

                    b.Property<int>("RuleId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("Domain.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("Result");

                    b.HasKey("Id");

                    b.ToTable("Rule");
                });

            modelBuilder.Entity("Domain.Condition", b =>
                {
                    b.HasOne("Domain.Rule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Outcomes", b =>
                {
                    b.HasOne("Domain.Rule", "Rule")
                        .WithMany("Outcomes")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
